version: "3.9"
services:
  epg:
    image: ghcr.io/aronhr/epg:main
    container_name: epg
    restart: unless-stopped
    environment:
      - TZ=UTC         # tryggir crontrigger sé í UTC
    volumes:
      - ./docker-services/epg/logs:/app/logs
      - ./docker-services/epg/data:/data      # <-- deilt á milli endurræsinga
    ports:
      - "34455:34455"
